medical_codes = [
    {"term": "Gunshot Wound Abdomen", "code": "S31.1", "price": 92000, "desc": "Open wound of abdominal wall"},
    {"term": "Compound Fracture Femur", "code": "S72.3", "price": 45000, "desc": "Broken thigh bone with open wound"},
    {"term": "Myocardial Infarction", "code": "I21.9", "price": 120000, "desc": "Acute heart attack"},
    {"term": "Appendicitis with Perforation", "code": "K35.2", "price": 35000, "desc": "Burst appendix with peritonitis"},
    {"term": "Bacterial Pneumonia", "code": "J15.9", "price": 12000, "desc": "Severe lung infection"},
    {"term": "Ischemic Stroke", "code": "I63.9", "price": 85000, "desc": "Blood clot in brain"},
    {"term": "Diabetic Ketoacidosis", "code": "E11.1", "price": 28000, "desc": "Severe diabetes complication"},
    {"term": "Deep Vein Thrombosis", "code": "I82.4", "price": 15000, "desc": "Blood clot in deep vein"},
    {"term": "Pulmonary Embolism", "code": "I26.9", "price": 55000, "desc": "Blood clot in lungs"},
    {"term": "Septic Shock", "code": "A41.9", "price": 95000, "desc": "Life-threatening infection response"},
    {"term": "Acute Renal Failure", "code": "N17.9", "price": 40000, "desc": "Sudden kidney failure"},
    {"term": "Traumatic Brain Injury", "code": "S06.9", "price": 110000, "desc": "Severe head trauma"},
    {"term": "Third Degree Burns 20%", "code": "T20.3", "price": 75000, "desc": "Severe burns requiring grafting"},
    {"term": "Ectopic Pregnancy", "code": "O00.9", "price": 32000, "desc": "Pregnancy outside uterus"},
    {"term": "Hypertensive Crisis", "code": "I16.9", "price": 18000, "desc": "Dangerously high blood pressure"},
    {"term": "Asthma Attack (Acute)", "code": "J45.9", "price": 8000, "desc": "Severe difficulty breathing"},
    {"term": "Meningitis (Bacterial)", "code": "G00.9", "price": 45000, "desc": "Infection of brain lining"},
    {"term": "Gastrointestinal Bleed", "code": "K92.2", "price": 38000, "desc": "Internal stomach/bowel bleeding"},
    {"term": "Pelvic Fracture", "code": "S32.8", "price": 60000, "desc": "Broken pelvic bones"},
    {"term": "Anaphylactic Shock", "code": "T78.2", "price": 12000, "desc": "Severe allergic reaction"},
    {"term": "Pancreatitis (Acute)", "code": "K85.9", "price": 25000, "desc": "Inflammation of pancreas"},
    {"term": "Cholera", "code": "A00.9", "price": 5000, "desc": "Severe diarrheal infection"},
    {"term": "Malaria (Severe)", "code": "B54", "price": 7500, "desc": "Advanced parasitic infection"},
    {"term": "Tuberculosis (Active)", "code": "A15.0", "price": 15000, "desc": "Infectious lung disease"},
    {"term": "Snake Bite with Venom", "code": "T63.0", "price": 22000, "desc": "Toxic envenomation"}
]